// Automatically generated by MockGen. DO NOT EDIT!
// Source: modules/exchange/exchange.go

package mock_exchange

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of eInterface interface
type MockeInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockeInterfaceRecorder
}

// Recorder for MockeInterface (not exported)
type _MockeInterfaceRecorder struct {
	mock *MockeInterface
}

func NewMockeInterface(ctrl *gomock.Controller) *MockeInterface {
	mock := &MockeInterface{ctrl: ctrl}
	mock.recorder = &_MockeInterfaceRecorder{mock}
	return mock
}

func (_m *MockeInterface) EXPECT() *_MockeInterfaceRecorder {
	return _m.recorder
}

func (_m *MockeInterface) save() boolean {
	ret := _m.ctrl.Call(_m, "save")
	ret0, _ := ret[0].(boolean)
	return ret0
}

func (_mr *_MockeInterfaceRecorder) save() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "save")
}
