// Automatically generated by MockGen. DO NOT EDIT!
// Source: modules/mailSender/mail.go

package mock_mail

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Mail interface
type MockMail struct {
	ctrl     *gomock.Controller
	recorder *_MockMailRecorder
}

// Recorder for MockMail (not exported)
type _MockMailRecorder struct {
	mock *MockMail
}

func NewMockMail(ctrl *gomock.Controller) *MockMail {
	mock := &MockMail{ctrl: ctrl}
	mock.recorder = &_MockMailRecorder{mock}
	return mock
}

func (_m *MockMail) EXPECT() *_MockMailRecorder {
	return _m.recorder
}

func (_m *MockMail) SendMail(s string, t string, o string) (bool, error) {
	ret := _m.ctrl.Call(_m, "SendMail", s, t, o)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockMailRecorder) SendMail(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SendMail", arg0, arg1, arg2)
}
